#!/bin/sh                                                                                                                         
pid=`ps aux|grep -v grep|grep -v $0 | grep "$*" | awk '{print $2}'`                                                               
kill -9 $pid                                                                                                                      
echo $pid   