#!/bin/sh                                                                                                                         
pid=`ps aux|grep -v grep|grep -v $0 | grep "$*" | awk '{print $2}'`                                                               
`ps aux|grep -v grep|grep -v $0 | grep "$*" | awk '{print $2}' | xargs -I {} echo {} && kill -9 {}`
